name: Automated Backup

on:
  schedule:
    - cron: "0 10 * * *" # Run daily at midnight UTC

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "Radiat09"
          git config user.email "radiathossainr@gmail.com"

      - name: Daily Backup
        run: |
          DATE=$(date +%Y-%m-%d)
          git checkout main
          git pull origin main
          git checkout -b backup/daily/$DATE
          git push origin backup/daily/$DATE

      - name: Weekly Backup
        if: ${{github.event_name == 'schedule' && formatTime(github.event.scheduledAt, 'EEEE') == 'Sunday' }}
        run: |
          WEEK=$(date +%Y-%V)
          git checkout main
          git pull origin main
          git checkout -b backup/weekly/$WEEK
          git push origin backup/weekly/$WEEK

      - name: Monthly Backup
        if: ${{ github.event_name == 'schedule' && formatTime(github.event.scheduledAt, 'dd') == '01' }}
        run: |
          MONTH=$(date +%Y-%m)
          git checkout main
          git pull origin main
          git checkout -b backup/monthly/$MONTH
          git push origin backup/monthly/$MONTH
