name: Backup Cleanup

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "Radiat09"
          git config user.email "radiathossainr@gmail.com"

      - name: Delete Old Backups
        run: |
          bash cleanup_script.sh
