name: on push

on:
  push:
    branches: "main"

jobs:
  run-bat:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run .bat File
        run: .\backup_script.bat
