name: Run .bat File

on:
  schedule:
    - cron: "0 15 * * *" # Run every day at 5:00 PM UTC

jobs:
  run-bat:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run .bat File
        run: .\backup_script.bat
